version: 0.2

phases:
  build:
    on-failure: ABORT
    commands:
      - $(aws ecr get-login --no-include-email --region eu-central-1)
      - source ./default_env_vars
      - docker-compose run integration_tests
      - docker-compose down
