version: 0.2

phases:
  build:
    on-failure: ABORT
    commands:
      - $(aws ecr get-login --no-include-email --region eu-central-1)
      - source ./default_env_vars
        # override TEST_RUNNER_IMAGE to always rebuild it from source
      - TEST_RUNNER_IMAGE=none docker-compose run integration_tests
      - docker-compose down
