
version: "3.4"

services:
  integration_tests:
    image: "${TEST_RUNNER_IMAGE}"
    depends_on:
      - test_service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["docker", "logs", "src_test_service_1"]

  test_service:
    image: "${TEST_SERVICE_IMAGE}"
